global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
    log-level: ""
    ics20-memo-limit: 0
    max-receiver-size: 0
chains:
    wasm-simapp-1:
        type: cosmos
        value:
            key-directory: /root/.relayer/keys/wasm-simapp-1
            key: rly-a
            chain-id: wasm-simapp-1
            rpc-addr: http://localhost:46657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01stake
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    gm:
        type: cosmos
        value:
            key-directory: /root/.relayer/keys/gm-key
            key: gm-key
            chain-id: gm
            rpc-addr: http://localhost:36657
            account-prefix: gm
            keyring-backend: test
            gas-adjustment: 2
            gas-prices: 1000000stake
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: [ ]
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: [ ]
            feegrants: null
paths:
    rollkit-path:
        src:
            chain-id: wasm-simapp-1
        dst:
            chain-id: gm
        src-channel-filter:
            rule: ""
            channel-list: [ ]
