global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
    log-level: ""
    ics20-memo-limit: 0
    max-receiver-size: 0
chains:
    gm:
        type: cosmos
        value:
            key-directory: /Users/chrly/.relayer/keys/gm
            key: gm-key-2
            chain-id: gm
            rpc-addr: http://rollkit:36657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uatom
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    wasm-simapp-1:
        type: cosmos
        value:
            key-directory: /Users/chrly/.relayer/keys/wasm-simapp-1
            key: rly1
            chain-id: wasm-simapp-1
            rpc-addr: http://wasm-simapp:46657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uatom
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths:
    demo-path:
        src:
            chain-id: gm
        dst:
            chain-id: wasm-simapp-1
        src-channel-filter:
            rule: ""
            channel-list: []
