type = "cosmos"
name = "simapp-1"
rpc_url = "http://127.0.0.1:26657"
grpc_url = "http://127.0.0.1:9090"
websocket_url = ""
chain_id = "simapp-1"
client_id = "07-tendermint-0"
connection_id = "connection-0"
account_prefix = "simapp"
fee_denom = "uatom"
fee_amount = "0"
gas_limit = 10000000000
store_prefix = "ibc"
max_tx_size = 20000000
wasm_code_id = "ddc292a095aa9b8625d5d7ebdd3a9c2301bda10a489385d560ecd3f7846fbb39"
channel_whitelist = [["channel-1", "transfer"]]
mnemonic = "mnemonic phrase example"
skip_optional_client_updates = true