type = "cosmos"
name = "wasm-simapp-2"
rpc_url = "http://wasm-simapp:56657"
grpc_url = "http://wasm-simapp:11290"
websocket_url = "ws://wasm-simapp:56657/websocket"
chain_id = "wasm-simapp-2"
account_prefix = "simapp"
fee_denom = "uatom"
fee_amount = "0"
gas_limit = 10000000000
store_prefix = "ibc"
max_tx_size = 20000000
channel_whitelist = [["channel-1", "transfer"]]
wasm_code_id = "ddc292a095aa9b8625d5d7ebdd3a9c2301bda10a489385d560ecd3f7846fbb39"
mnemonic = "alley afraid soup fall idea toss can goose become valve initial strong forward bright dish figure check leopard decide warfare hub unusual join cart"
skip_optional_client_updates = true