type = "cosmos"
name = "gm"
rpc_url = "http://127.0.0.1:26658"
grpc_url = "http://127.0.0.1:9290"
websocket_url = ""
chain_id = "gm"
client_id = "07-tendermint-0"
connection_id = "connection-0"
account_prefix = "gm"
fee_denom = "uatom"
fee_amount = "0"
gas_limit = 10000000000
store_prefix = "ibc"
max_tx_size = 20000000
wasm_code_id = "HERE IS THE WASM CODE"
channel_whitelist = [["channel-1", "transfer"]]
mnemonic = "mnemonic phrase example"
skip_optional_client_updates = true
