---
version: "3.8"
services:
  celestia-dev:
    hostname: celestia
    image: ghcr.io/rollkit/local-celestia-devnet:v0.12.7
    ports:
      - "26657"
      - "26650"
      - "26658"
      - "26659"
      - "9090"

  wasm-simapp:
    image: wasm-simapp:latest
    command: [ "/bin/sh", "-c", "/wasm-init.sh && simd start" ]
    entrypoint: [ "" ]
    volumes:
      - ./wasm-init.sh:/wasm-init.sh
      - ./contracts/ics07_tendermint_cw.wasm:/ics07_tendermint_cw.wasm
      - ./scripts/update-genesis.py:/update-genesis.py
    ports:
      - "46657:26657"
      - "10290:9290"

  rollkit-app:
    depends_on:
      - celestia-dev
    image: rollkit:latest
    # wait 5 seconds to give celestia time to start
    command: [ "/bin/sh", "-c", "sleep 5 && /init-local.sh" ]
    entrypoint: [ "" ]
    volumes:
      - ./init-local.sh:/init-local.sh
    ports:
      - "36656"
      - "36657"
      - "9290"