---
version: "3.8"
services:
  # celestia-dev:
  #   # hostname: celestia
  #   network_mode: "host"
  #   image: ghcr.io/rollkit/local-celestia-devnet:v0.12.7
  #   ports:
  #     - "26657"
  #     - "26650"
  #     - "26658"
  #     - "26659"
  #     - "9090"
  #   healthcheck:
  #     # considered healthy if the /block endpoint returns a 200 status code
  #     test: curl http://localhost:26657/block
  #     interval: 5s
  #     retries: 5
  #     start_period: 1s
  #     timeout: 10s

  wasm-simapp:
    # hostname: wasm-simapp
    network_mode: "host"
    image: wasm-simapp:latest
    command: [ "/bin/sh", "-c", "/wasm-init.sh" ]
    entrypoint: [ "" ]
    volumes:
      - ./wasm-init.sh:/wasm-init.sh
      - ./contracts/ics07_tendermint_cw.wasm:/ics07_tendermint_cw.wasm
      - ./scripts/update-genesis.py:/update-genesis.py
    #    ports:
    #      - "46657"
    #      - "10290"
    #      - "6060"
    environment:
      - "CHAIN_ID=wasm-simapp-1"

  wasm-simapp-2:
    # hostname: wasm-simapp-2
    network_mode: "host"
    image: wasm-simapp:latest
    command: [ "/bin/sh", "-c", "/wasm-init-2.sh" ]
    entrypoint: [ "" ]
    volumes:
      - ./wasm-init-2.sh:/wasm-init-2.sh
      - ./contracts/ics07_tendermint_cw.wasm:/ics07_tendermint_cw.wasm
      - ./scripts/update-genesis.py:/update-genesis.py
    #    ports:
    #      - "56657"
    #      - "11290"
    #      - "6061"
    environment:
      - "CHAIN_ID=wasm-simapp-2"

  #  rollkit-app:
  #    hostname: rollkit
  #    depends_on:
  #      celestia-dev:
  #        # wait for the celestia endpoints to be accessible.
  #        condition: service_healthy
  #    image: rollkit:latest
  #    # wait 5 seconds to give celestia time to start
  #    command: [ "/bin/sh", "-c", "/init-local.sh" ]
  #    entrypoint: [ "" ]
  #    volumes:
  #      - ./init-local.sh:/init-local.sh
  #    ports:
  #      - "36656"
  #      - "36657"
  #      - "9290"

  #   hyperspace:
  #     image: ghcr.io/misko9/hyperspace:20231122v39
  #     depends_on:
  #       # - rollkit-app
  #       - wasm-simapp
  # #      - wasm-simapp-2
  #     entrypoint: [ "" ]
  #     command: [ "/bin/sh", "-c", "sleep 10 && /init-hyperspace.sh" ]
  #     volumes:
  #       - ./test_configs:/test_configs
  #       - ./init-hyperspace.sh:/init-hyperspace.sh

  rly:
    image: ghcr.io/charleenfei/relayer:feat-tm_wasm_support
    depends_on:
      - wasm-simapp
      - wasm-simapp-2
    entrypoint: [""]
    command: [ "/bin/sh", "-c", "sleep 10 && /init-rly.sh" ]
    volumes:
       - ./test_configs/:/root/.relayer/config/config.yaml
       - ./test_configs:/test_configs
       - ./init-rly.sh:/init-rly.sh
