on:
  push:

jobs:
  docker-build-rollkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ghcr.io/chatton/gm

      - name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: gm
          file: Dockerfile.local
          push: true
          tags: ${{ steps.meta.outputs.tag }}

  docker-build-wasm:
    runs-on: ubuntu-latest
    steps:
        # checkout ibc-go feature branch
      - uses: actions/checkout@v4
        repository: 'cosmos/ibc-go'
        ref: 'feat/rollkit'
        fetch-tags: 'feat/rollkit'
        path: 'ibc-go'

      - uses: actions/checkout@v4
        path: 'gm-demo'

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wasm simapp
        run: |
          cd ibc-go
          make build-docker-wasm tag=ibc-go-wasm-simd:latest
          
          cd ../gm-demo/gm
          make build-docker-wasm
          
          docker tag wasm-simapp:latest ghcr.io/chatton/ibc-go-wasm-simd:latest
          docker push ghcr.io/chatton/ibc-go-wasm-simd:latest
