on:
  push:

jobs:
  docker-build-rollkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ inputs.build-and-push-docker-image }}
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ghcr.io/chatton/rollkit

      - name: Build and push Rollkit Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: gm
          push: true
          tags: ${{ steps.meta.outputs.tags }}


  docker-build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'cosmos/ibc-go'
          ref: 'feat/rollkit'
          fetch-tags: 'feat/rollkit'
          path: 'ibc-go'

      - uses: actions/checkout@v4
        with:
          path: 'gm-demo'

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wasm simapp (ibc-go)
        run: |
          cd ibc-go
          make build-docker-wasm tag=ibc-go-wasm-simd:latest

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ inputs.build-and-push-docker-image }}
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ghcr.io/chatton/ibc-go-wasm-simd

      - name: Build and push Wasm Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: gm
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile.wasm
